### ISSUE TITLE
make a profile link !!

### ISSUE THREAD

**Issue by numanzamandipuu** [AlgoJect/Legends#2]
please make three buttons on your homepage. these will contain three different links to our profiles.

**Comment by FahadBinHussain** [comment]
> please make three buttons on your homepage. these will contain three different links to our profiles.

ok, on it

**Comment by FahadBinHussain** [comment]
@numanzamandipuu ok, on it again

**Comment by numanzamandipuu** [comment]
but now on it where -_-

**Comment by FahadBinHussain** [comment]
on dreamweaver 😀

**Comment by numanzamandipuu** [comment]
kindly decide a final name for that website skipper -_-

**Comment by FahadBinHussain** [comment]
I think LEGENDS™️ will be alright

**Comment by numanzamandipuu** [comment]
nope, AlgoJect will be nice.

**Comment by FahadBinHussain** [comment]
ok 😀
